#!/usr/bin/env bash
# displaying list of currently running processes
#all processes, for all users, including those without those with TTy
# user-oriented format
# Shows process hierarchy

ps -u -a -x -f 
